<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9cd96158-3f82-468f-ae11-39bdb72e64e9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TemplateMaster.AspNetCore" Version="1.0.228" />
  </ItemGroup>

</Project>
